Frontend Changes
Ilhasoft/health-buddy-admin pull request #39
Opened 2021-08-17 13:03 UTC by mehedi-rul

Modified:
- Login page changed to logo,text and button color and logo background color

Added:
- Active poll, Archived poll, manage poll field has been added to the side navbar on Dashboard.
- Added Dynamic Iframe Active poll, Archived poll.
- Active poll, Archived poll, manage poll activities has been added new icon.
- Addad a new field in the user section table and new user and edit user page, its name is Agency. And customized fields FirstName and LastName to Name.
- Added a new field in the edit user page, its name is Active.
- Addad a new manage poll section table with new user and edit user.

2021-08-17 13:05 UTC, mehedi-rul commented
v1.5.5 Active poll, Archived poll, manage poll update

2021-08-18 14:21 UTC, paulobernardoaf requested changes
Run `yarn lint` after making changes

2021-08-18 14:21 UTC, paulobernardoaf commented on src/views/managePoll.vue
> +        this.data.id = this.data.id;
Is this really correct?

2021-08-18 14:21 UTC, paulobernardoaf commented on src/views/User.vue
> +        console.log(this.data.is_active);
Please remove console

2021-08-25 07:10 UTC, mehedi-rul commented on CHANGELOG.md
> +release v1.5.5
done

2021-08-25 07:11 UTC, mehedi-rul commented
This issue has been resolved

2021-08-25 13:54 UTC, paulobernardoaf approved these changes

2021-08-31 21:45 UTC, merged